# Generated by Django 3.1.2 on 2020-10-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='document',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
